"""Write the prompts every stage sends, verbatim from the code, into docs/HARNESS.md (between the prompt markers), so
the harness description never drifts from what the harness does.

    python3 scripts/harness_prompts.py
"""
import importlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "eval"))
DOC = os.path.join(ROOT, "docs", "HARNESS.md")
START, END = "<!-- prompts:start (generated by scripts/harness_prompts.py; do not edit by hand) -->", "<!-- prompts:end -->"

# (section, [(module, constant, what it is for)])
PROMPTS = [
    ("A. Delegated reading (prepare)", [
        ("swarmgraph.sweep", "PROMPT", "sweep: one chunk of ONE agent's working record (transcripts)"),
        ("swarmgraph.sweep", "GROUP", "sweep: one chunk of a log where several actors act (boards, chats, wikis)"),
        ("swarmgraph.sweep", "ASK", "delegate: the analyst's own question, asked of chosen chunks"),
        ("swarmgraph.sweep", "RULES", "rules: instructions and commitments of one period merged into standing rules"),
        ("swarmgraph.sweep", "THREAD", "threads: a later chunk of one agent's record read against the rules in force"),
        ("swarmgraph.sweep", "THREAD_GROUP", "threads: the same for a multi-actor log"),
        ("swarmgraph.sweep", "TRACE", "trace: later statements read against the earlier chunk where the agent made "
                                      "the thing they describe"),
        ("swarmgraph.ledger", "CHECK", "ledger (action layer): one case of a claim set against the record"),
    ]),
    ("B. Storyline", [
        ("swarmgraph.storyline", "PERIOD", "one period's summary and turning points, from its digest"),
        ("swarmgraph.storyline", "OVERALL", "the overview and storylines, from the period summaries"),
        ("swarmgraph.storyline", "SHARE", "the share-mode rewrite for readers outside the investigation"),
    ]),
    ("C. Behaviour features", [
        ("swarmgraph.features", "INDUCE", "proposing behaviours from sampled stretches (UNIT_FORMAT is included)"),
        ("swarmgraph.features", "MERGE", "merging every proposal into one dictionary"),
        ("swarmgraph.features", "JUDGE", "marking behaviours event by event (calibration judges, more judging, the "
                                         "flow sample)"),
        ("swarmgraph.features", "DETECT", "the blind detection test"),
        ("swarmgraph.features", "SHORT", "short names for the map"),
    ]),
    ("D. The arc", [
        ("swarmgraph.arc", "ARC", "the arc from the code skeleton and the storyline (arc)"),
        ("swarmgraph.arc", "REVIEW", "its reviewer"),
        ("swarmgraph.arc", "UNDATED", "a reader of material the dataset kept apart from the timeline"),
        ("swarmgraph.arc", "AGENT", "the arc written by an analyst that queries the flow tools (arc --agent)"),
        ("swarmgraph.arc", "AGENT_REVIEW", "its reviewer, given the same measurements and the cited events"),
    ]),
    ("E. Stories on demand (the atlas page)", [
        ("swarmgraph.incident_storylines", "DISCOVERY_PROMPT", "scout: possible connected incidents"),
        ("swarmgraph.incident_storylines", "WRITER_PROMPT", "writer: the public account"),
        ("swarmgraph.incident_storylines", "REVIEW_PROMPT", "reviewer: an independent check of the account"),
    ]),
    ("F. Evaluation", [
        ("analyst_ab", "HYP_BASE", "an analyst asked for behaviour hypotheses"),
        ("analyst_ab", "EXTRA", "what an analyst with the prepared index is told"),
        ("analyst_ab", "EXTRA_FEAT", "the flow round, arm without the flow tools"),
        ("analyst_ab", "EXTRA_FLOW", "the flow round, arm with the flow tools"),
        ("hyp_test", "FORMALIZE", "a condition-blind formalizer: hypotheses into tests over event text"),
        ("flow_grade", "FORM", "a condition-blind formalizer: hypotheses into flow claims over the dictionary"),
    ]),
    ("G. Earlier layers still in the package", [
        ("swarmgraph.tags", "PROMPT", "one note per event (the notes layer)"),
        ("swarmgraph.cards", "TRAJ_PROMPT", "trajectory card of an actor, channel or the swarm"),
        ("swarmgraph.cards", "LINK_PROMPT", "how two actors are connected"),
        ("swarmgraph.cards", "SWARM_PROMPT", "how the whole swarm's behaviour developed"),
        ("swarmgraph.cards", "STORY_PROMPT", "the earlier story for people"),
        ("swarmgraph.themes", "DISCOVER", "recurring themes from event notes"),
        ("swarmgraph.themes", "RATE", "how much an investigator would want to open each theme"),
        ("swarmgraph.themes", "ASSIGN", "assigning themes to events"),
        ("swarmgraph.alignment", "ENV_PROMPT", "the environment inferred blind"),
        ("swarmgraph.alignment", "CONCERN_PROMPT", "events reviewed for possibly misaligned behaviour"),
        ("swarmgraph.alignment", "CARD_PROMPT", "briefing an overseer on an actor's concerns"),
        ("swarmgraph.atlas", "NAME", "naming a kind of behaviour (behaviour map, version 1)"),
        ("swarmgraph.atlas", "CHECK", "its blind check"),
        ("swarmgraph.auto", "GEN_PROMPT", "auto: generating hypotheses from signals"),
        ("swarmgraph.auto", "INV_PROMPT", "auto: advocate and skeptic verifiers"),
        ("swarmgraph.auto", "JUDGE_PROMPT", "auto: the judge"),
        ("swarmgraph.summarize", "PROMPT", "an actor's summary in one segment"),
        ("swarmgraph.feature_storylines", "WRITER_PROMPT", "the earlier narrated atlas tour"),
        ("swarmgraph.feature_storylines", "REVIEW_PROMPT", "its reviewer"),
    ]),
]


def block():
    out = [START, ""]
    for section, items in PROMPTS:
        out += [f"### {section}", ""]
        for mod, name, what in items:
            text = getattr(importlib.import_module(mod), name)
            fence = "~~~~~"
            assert fence not in text
            path = mod.replace(".", "/") + ".py" if mod.startswith("swarmgraph") else f"eval/{mod}.py"
            out += [f"**`{path}` · `{name}`**: {what}", "",
                    fence + "text", text.rstrip("\n"), fence, ""]
    out.append(END)
    return "\n".join(out)


def main():
    doc = open(DOC).read()
    a, b = doc.index(START), doc.index(END) + len(END)
    open(DOC, "w").write(doc[:a] + block() + doc[b:])
    print(f"{DOC}: {sum(len(i) for _, i in PROMPTS)} prompts written")


if __name__ == "__main__":
    main()
